### ISSUE TITLE
Can't play some songs 

### ISSUE THREAD

**Issue by Yogimoturi** [Harsh-23/Musify#6]
First of all this is an awesome idea and the app is so simple to use but I can't actually play some songs in the app I attached the screenshot, hope you can fix it and thanks again 
![Screenshot_2020-08-15-13-56-07-787_com example music](https://user-images.githubusercontent.com/42579330/90308759-f3691b80-deff-11ea-89be-ce4767dfa0cc.jpg)

**Comment by cyberboysumanjay** [comment]
Should be fixed by this commit https://github.com/Harsh-23/Musify/commit/4048806d5f3fce134c3f7cb0bb1075db37d4afcc

**Comment by cyberboysumanjay** [comment]
Fixed in [v2.1.0](https://github.com/Harsh-23/Musify/releases/tag/v2.1.0)
